import java.io.IOException;

public class helloworld {
    private static byte[] data = new byte[256];
    private static byte ptr = 0;
    
    public static void main(String[] args) throws IOException {
        // end of header
        data[ptr] += 1;
        data[ptr] += 1;
        data[ptr] += 1;
        data[ptr] += 1;
        data[ptr] += 1;
        data[ptr] += 1;
        data[ptr] += 1;
        data[ptr] += 1;
        data[ptr] += 1;
        data[ptr] += 1;
        do {
            ptr += 1;
            data[ptr] += 1;
            data[ptr] += 1;
            data[ptr] += 1;
            data[ptr] += 1;
            data[ptr] += 1;
            data[ptr] += 1;
            data[ptr] += 1;
            ptr += 1;
            data[ptr] += 1;
            data[ptr] += 1;
            data[ptr] += 1;
            data[ptr] += 1;
            data[ptr] += 1;
            data[ptr] += 1;
            data[ptr] += 1;
            data[ptr] += 1;
            data[ptr] += 1;
            data[ptr] += 1;
            ptr += 1;
            data[ptr] += 1;
            data[ptr] += 1;
            data[ptr] += 1;
            ptr += 1;
            data[ptr] += 1;
            ptr += -1;
            ptr += -1;
            ptr += -1;
            ptr += -1;
            data[ptr] += -1;
        } while (data[ptr] != 0);
        ptr += 1;
        data[ptr] += 1;
        data[ptr] += 1;
        System.out.print((char) data[ptr]);
        ptr += 1;
        data[ptr] += 1;
        System.out.print((char) data[ptr]);
        data[ptr] += 1;
        data[ptr] += 1;
        data[ptr] += 1;
        data[ptr] += 1;
        data[ptr] += 1;
        data[ptr] += 1;
        data[ptr] += 1;
        System.out.print((char) data[ptr]);
        System.out.print((char) data[ptr]);
        data[ptr] += 1;
        data[ptr] += 1;
        data[ptr] += 1;
        System.out.print((char) data[ptr]);
        ptr += 1;
        data[ptr] += 1;
        data[ptr] += 1;
        System.out.print((char) data[ptr]);
        ptr += -1;
        ptr += -1;
        data[ptr] += 1;
        data[ptr] += 1;
        data[ptr] += 1;
        data[ptr] += 1;
        data[ptr] += 1;
        data[ptr] += 1;
        data[ptr] += 1;
        data[ptr] += 1;
        data[ptr] += 1;
        data[ptr] += 1;
        data[ptr] += 1;
        data[ptr] += 1;
        data[ptr] += 1;
        data[ptr] += 1;
        data[ptr] += 1;
        System.out.print((char) data[ptr]);
        ptr += 1;
        System.out.print((char) data[ptr]);
        data[ptr] += 1;
        data[ptr] += 1;
        data[ptr] += 1;
        System.out.print((char) data[ptr]);
        data[ptr] += -1;
        data[ptr] += -1;
        data[ptr] += -1;
        data[ptr] += -1;
        data[ptr] += -1;
        data[ptr] += -1;
        System.out.print((char) data[ptr]);
        data[ptr] += -1;
        data[ptr] += -1;
        data[ptr] += -1;
        data[ptr] += -1;
        data[ptr] += -1;
        data[ptr] += -1;
        data[ptr] += -1;
        data[ptr] += -1;
        System.out.print((char) data[ptr]);
        ptr += 1;
        data[ptr] += 1;
        System.out.print((char) data[ptr]);
        ptr += 1;
        System.out.print((char) data[ptr]);
        // start of footer
    }
}
